- hosts: vm2
  tasks:
  - name: Install git
    yum:
      name: git
      state: latest

  - name: Clone app Repo
    git:
      repo: https://github.com/ikambarov/Flaskex
      dest: /Flaskex

  - name: Install pip
    shell: "curl -s https://bootstrap.pypa.io/pip/2.7/get-pip.py | python"

  - name: pip requirements
    pip:
      requirements: /Flaskex/requirements.txt
  
  - name: Start app
    shell: "pkil app.py; nohup python app.py &"
    args:
      chdir: /Flaskex