- hosts: all
  tasks:
  - name: Install Git
    import_role: 
      name: ansible-git-role

  - name: Clone app Repo
    git:
      repo: https://github.com/ikambarov/Flaskex
      dest: /Flaskex
  
  - name: Install pip
    import_role: 
      name: ansible-pip-role
  
  - name: pip requirements
    pip:
      requirements: /Flaskex/requirements.txt
  
  - name: Start app
    shell: "pkil app.py; nohup python app.py &"
    args:
      chdir: /Flaskex